tasks:
  - name: app
    init: |
      pip install -r requirements.txt
      npm i -g nodemon
      export PORT=3000
      echo the defined PORT in the 'init' is: $PORT
    command: |
      nodemon app.py

ports:
  - port: 3000

